name: dot_coaching
description: "A visual coaching app."
publish_to: "none"
version: 1.0.1+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.5.0+1
  intl: ^0.19.0
  firebase_analytics: ^11.2.1
  firebase_core: ^3.3.0
  firebase_crashlytics: ^4.0.4
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  path_provider: ^2.1.4
  logger: ^2.4.0
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.0
  google_fonts: ^6.2.1
  syncfusion_flutter_calendar: ^26.2.8
  image_picker: ^1.1.2
  image_cropper: ^8.0.1
  dotted_border: ^2.1.0
  buttons_tabbar: ^1.3.13
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  file_picker: ^8.0.0+1
  text_area: ^0.0.3
  easy_debounce: ^2.0.3
  skeletonizer: ^1.4.2
  firebase_messaging: ^15.0.4
  web_socket_channel: ^3.0.1
  chewie: ^1.7.5
  video_player: ^2.9.1
  injectable: ^2.4.4
  auto_route: ^9.2.0
  moon_design: ^1.0.3
  gap: ^3.0.1
  elegant_notification: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  icons_launcher: ^2.1.7
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.6.0
  bloc_test: ^9.1.7
  http_mock_adapter: ^0.6.1
  mockito: ^5.4.4
  injectable_generator: ^2.4.2
  auto_route_generator: ^9.0.0

dependency_overrides:
  analyzer: ^6.2.0

flutter_gen:
  output: lib/core/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/google_fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/google_fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/google_fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/google_fonts/Montserrat-Black.ttf
          weight: 900

  assets:
    - assets/google_fonts/
    - assets/icons/
    - assets/images/
    - assets/images/bg/
    - assets/images/exam/
    - assets/images/hero/
    - assets/images/placeholder/
    - shorebird.yaml
