// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChHx137Aqvembif13RhqM7gxYM4gRvVVM',
    appId: '1:362661479175:web:ad7e9b8a4aea5f59763ba2',
    messagingSenderId: '362661479175',
    projectId: 'dot-coaching',
    authDomain: 'dot-coaching.firebaseapp.com',
    storageBucket: 'dot-coaching.appspot.com',
    measurementId: 'G-FLL73N5LH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAVpWcmP7eXHOi4dtssWgvJohZOU4AO9A',
    appId: '1:362661479175:android:44b175974939f5f8763ba2',
    messagingSenderId: '362661479175',
    projectId: 'dot-coaching',
    storageBucket: 'dot-coaching.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ2_uTIkdbIYS7NVvk-RarpHadb8W2m_Q',
    appId: '1:362661479175:ios:0462364fffb020cb763ba2',
    messagingSenderId: '362661479175',
    projectId: 'dot-coaching',
    storageBucket: 'dot-coaching.appspot.com',
    iosBundleId: 'dev.zenta.doting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChHx137Aqvembif13RhqM7gxYM4gRvVVM',
    appId: '1:362661479175:web:0654a8322e92e324763ba2',
    messagingSenderId: '362661479175',
    projectId: 'dot-coaching',
    authDomain: 'dot-coaching.firebaseapp.com',
    storageBucket: 'dot-coaching.appspot.com',
    measurementId: 'G-HSRZ614NRZ',
  );
}
